services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: datungratyeu1cogai
      MYSQL_DATABASE: drum_store
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: datungratyeu1cogai
    ports:
      - "8080:80"
    depends_on:
      - mysql
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/drum_store
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: datungratyeu1cogai
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      JAVA_OPTS: "--enable-preview"

volumes:
  mysql_data:
